### PR TITLE
feat: add WatchMissingNodeModulesPlugin from react-dev-utils

### PR DESCRIPTION
**Pull request by christophehurpeau**

### CODE REVIEW

**Comment by christophehurpeau** [comment]
@johangirod this doesn't work well...

**Comment by johangirod** [comment]
Ok I won't merge ;)

**Comment by alepee** [comment]
Is this PR still active? @christophehurpeau

**Comment by christophehurpeau** [comment]
@alepee you can try it and see if it works well :)

**Comment by alepee** [comment]
will try shortly ;)

**Comment by alepee** [comment]
This Webpack plugin ensures npm install <library> forces a project rebuild.
We’re not sure why this isn't Webpack's default behavior.
See [#186](https://github.com/facebookincubator/create-react-app/issues/186) for details.

```
var path = require('path');
var WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
 
// Webpack config 
module.exports = {
  // ... 
  plugins: [
    // ... 
    // If you require a missing module and then `npm install` it, you still have 
    // to restart the development server for Webpack to discover it. This plugin 
    // makes the discovery automatic so you don't have to restart. 
    // See https://github.com/facebookincubator/create-react-app/issues/186 
    new WatchMissingNodeModulesPlugin(path.resolve('node_modules'))
  ],
  // ... 
}
```

https://www.npmjs.com/package/react-dev-utils#new-watchmissingnodemodulespluginnodemodulespath-string

**Pull request merged**
