### PR TITLE
fix(webpack-config): add support for css-modules value

### PR DESCRIPTION
**Pull request by johangirod**
- Add support for css-modules value 
- Change loader options from query string to object
- Complete Counter example with css module value & url example

Supercede https://github.com/Evaneos/vitaminjs/pull/261

### CODE REVIEW

**Comment by johangirod** [comment]
@christophehurpeau we need to add postcssUrl after all.
See https://github.com/postcss/postcss-url/issues/64#issuecomment-182584192

**Comment by alepee** [comment]
@johangirod about this PR? Is reviewable for you?

**Comment by johangirod** [comment]
@alepee, yeup, forgot about it, but it's definitely something that we should merge asap.

**Comment by johangirod** [comment]
@alepee, yes, it's in the official specification, so that's definitly something we ought to support if we are pretending to have css-modules in vitaminJS

**Pull request merged**
