### PR TITLE
[Breaking] Better error handling with vitaminjs

### PR DESCRIPTION
**Pull request by johangirod**
### [BC] ErrorPage
VitaminJS accept now only one ErrorPage component that will be rendered on error (insteand of the `Error500Page` and the `Error404Page`. The component is given all contextual information needed for displaying additional info (the error object, the status, the request, and the redux state)

### onError
Add an the possibility to specify an `onError` function, called when rendering error occurs server side (404, 500, ...)
```es6
onError = ({ HTTPStatus, request, error, state }) => ...
```

### Better console message
Console is now coloured, and the error message are stripped down to the minimum for better readability.

### CODE REVIEW

**Comment by christophehurpeau** [comment]
why not event emitter ?

**Comment by johangirod** [comment]
I thought about it (I guess you mean using an event emitter like [koa for notifying errors](http://koajs.com/#application)). The problem is that vitamin does not expose any object to use as an event emitter. We embrasse inversion of control for server-side rendering, so the user cannot have access to the app object. 

The other solution might be to expose the app object though a callback, but I'm not really fond of this as it expose the internals of vitamin.

This solution have the advantage to provide a minimal api for achieving error logging, without putting too much restrictions.

**Comment by johangirod** [comment]
Ok, I cleaned things up on error handling.

Now we have two user-specified keys for handling error on server in vitaminjs : 
- ErrorPage : A react component displayed when an error occured during rendering
- onError : A function called when an error occured during rendering

Both have exactly the same signature. 
- `HTTPStatus`: the error throwed. Useful for printing stack. Only passed when in dev mode.
- `context`: An object containing additional informations about the error.
    - `request`: The koa request object
    - `error` (optional): If the page is displayed because of an error thrown during rendering (500)
    you'll find here the javascript Error object (with the usual `name`, `message` and `stack` props)
    - `store` (optional): The redux store object, if it's present

But then I thought... is it even necessary to have a `onError`function ? We can log everything we want inside the `componentWillMount` lifecycle hook of the ErrorPage component. It narrows down the API to a single endpoint, which I tend to prefer.

What are your thought ? 
Yay ? Nay ?

**Comment by johangirod** [comment]
Ok I just answered my own question by realizing that you will want to log if your ErrorPage component crashes during rendering. So definitely two separate API.

**Pull request merged**
