### PR TITLE
render Helmet scripts into document header

### PR DESCRIPTION
**Pull request by alepee**
script async attributes should be used to make a script loading
non-blocking instead of including scripts at body’s tail.

### CODE REVIEW

**Comment by christophehurpeau** [comment]
@johangirod fix a bug because helmet on loading change scripts in the body to the head

**Comment by alepee** [comment]
We did not merged this pull request yet. Do we still need it after @Taskim changes?

**Comment by johangirod** [comment]
Well, I'm not sure. You should check if you still have the bug.
I'm not really convinced by relying on the user use of async anyway. I prefer to be sure that the script do not block the rendering by putting them at the end.

**Comment by christophehurpeau** [comment]
@johangirod problem is that react-helmet removes scripts and put them back in the head, so there are loaded twice and it causes issues

**Comment by alepee** [comment]
and yes I still get this issue with current vitamin state. I had to override `htmlLayout.jsx`

**Comment by christophehurpeau** [comment]
related: https://github.com/nfl/react-helmet/issues/141

**Comment by christophehurpeau** [comment]
But I think anyway that scripts should be in the head to ask the browser to download them as soon as possible

**Comment by johangirod** [comment]
If we merge this PR, we'll need other adjustements. I'm thinking about the following scenario :

- The js script in the header is in cache, it loads instantly.
- It starts to be executed while the DOM is loading
- The INITIAL_STATE of redux is still not parsed
- The app initialize without the server state

I think the easiest way to solve this would be to have a onContentLoad on the bootstrapClient() method.

**Comment by christophehurpeau** [comment]
@johangirod or use defer instead of async ?

**Comment by johangirod** [comment]
Didn't know about defer attribute \o/
That would do the trick, indeed :)

SO you might want to rebase this PR, and add a defer attributes to the main app js file.

**Pull request closed without merging**
