### PR TITLE
<fix> Script tag position containing server initialState

### PR DESCRIPTION
**Pull request by LucasPerso**
This commit fixes a bug where the initialState was not always correctly parsed by the server and then creating an error when the client tries to access it.

### CODE REVIEW

**Comment by johangirod** [comment]
I'm not sure I agree. If you do that, the browser will need to parse the whole state before it can display the rest of the page. It adds an unecessary overhear on init time. I don't get the problem with having the script at the end of the page. Could you explain a little bit more ? 
@christophehurpeau @LucasPerso

**Comment by christophehurpeau** [comment]
@johangirod async has no effect on inline scripts
We don't know why, but sometimes INITIAL_STATE is not parsed. Putting it before seems to fix...

**Comment by christophehurpeau** [comment]
@johangirod I'm not a fan of the INITIAL_STATE being a string, any reason for it ?

**Comment by johangirod** [comment]
Well, we might want to investigate why the inital state was not parsed in the first place... 
I'll look into it

**Pull request merged**
