### PR TITLE
context replacement

### PR DESCRIPTION
**Pull request by christophehurpeau**
- [ ] Api
- [ ] Doc

### CODE REVIEW

**Comment by christophehurpeau** [comment]
Note: module contexts is deprecated (https://webpack.js.org/configuration/module/#module-contexts)

**Comment by alepee** [comment]
Is this PR still active? @christophehurpeau

**Comment by christophehurpeau** [comment]
@alepee no, but related to #56 and someone should work on it :)

**Comment by alepee** [comment]
ok thanks :)

**Pull request closed without merging**
