### PR TITLE
babel 6.20

### PR DESCRIPTION
**Pull request by christophehurpeau**
Related: babel/babel#4883

### CODE REVIEW

**Comment by johangirod** [comment]
Yay ! It's all good for me 👍

**Comment by christophehurpeau** [comment]
still has issues : https://github.com/babel/babel/issues/4851

**Comment by christophehurpeau** [comment]
fix in PR : https://github.com/babel/babel/pull/5088

**Comment by christophehurpeau** [comment]
https://github.com/Evaneos/vitaminjs/pull/211

**Pull request closed without merging**
